### ISSUE TITLE
Missing library even though it's installed

### ISSUE THREAD

**Issue by kistanovdev** [wladradchenko/wunjo.wladradchenko.ru#21]
```zsh
$ brew list | grep snd
libsndfile
```
```python
$ briefcase dev

[wunjo] Starting in dev mode...
===========================================================================
objc[30653]: Class AVFFrameReceiver is implemented in both /opt/homebrew/Cellar/ffmpeg/6.0_1/lib/libavdevice.60.1.100.dylib (0x29c580370) and /Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/av/.dylibs/libavdevice.59.7.100.dylib (0x2a75d8778). One of the two will be used. Which one is undefined.
objc[30653]: Class AVFAudioReceiver is implemented in both /opt/homebrew/Cellar/ffmpeg/6.0_1/lib/libavdevice.60.1.100.dylib (0x29c5803c0) and /Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/av/.dylibs/libavdevice.59.7.100.dylib (0x2a75d87c8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kistanov/.pyenv/versions/3.10.12/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/kistanov/.pyenv/versions/3.10.12/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/kistanov/.pyenv/versions/3.10.12/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/portable/src/wunjo/__main__.py", line 1, in <module>
    from wunjo.app import main
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/portable/src/wunjo/app.py", line 15, in <module>
    from deepfake.inference import AnimationMouthTalk, AnimationFaceTalk, FaceSwap, Retouch, VideoEdit
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/portable/src/deepfake/inference.py", line 24, in <module>
    from src.generate_batch import get_data
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/portable/src/deepfake/src/generate_batch.py", line 8, in <module>
    import src.utils.audio as audio
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/portable/src/deepfake/src/utils/audio.py", line 1, in <module>
    import librosa
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Users/kistanov/github/wunjo.wladradchenko.ru/venv3.10.12/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file)

```

**Comment by wladradchenko** [comment]
Hello,

From the error log you provided, it's evident that there's an issue related to the `soundfile` library not being able to locate the required `libsndfile` file. 

Even though `brew list | grep snd` indicates that `libsndfile` is installed, the challenge here appears to be tied to the changes introduced with the M1 Macs. Starting with the M1 architecture, Homebrew defaults to installing in `/opt/homebrew`, which might lead to discrepancies in locating the necessary include and library files.

To address this:

1. Set the path for Homebrew's include and library directories:
```
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```

2. Then, try recompiling your application. 

To ensure these settings persist for future use, append the above lines to your shell's `.zprofile` (or `.profile`).

3. As a fallback, you can locate the `libsndfile` and manually copy it into `/usr/local/include`.

For more comprehensive solutions and to troubleshoot potential issues with the new MacOS M chip, refer to our repository's issue section: [here](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/14).

Hope this helps!
