### ISSUE TITLE
Не создается exe файл в каталоге portable\build после команды briefcase build

### ISSUE THREAD

**Issue by anrej0705** [wladradchenko/wunjo.wladradchenko.ru#32]
Привет, я не могу найти созданный .exe файл, как писалось в вики, который должен появиться после выполнения команды briefcase build. Но его там нет. Файл который я нашёл в папке src, которая лежит по пути portable\build\wunjo\windows\app\src не запускается, давая ошибки: 

> Traceback (most recent call last):
  File "\app\wunjo\__main__.py", line 1, in <module>
    from wunjo.app import main
  File "\app\wunjo\app.py", line 17, in <module>
    from diffusers.inference import Video2Video, create_diffusion_instruction
  File "\app\diffusers\inference.py", line 17, in <module>
    from src.utils.video2render import render
  File "\app\diffusers\src\utils\video2render.py", line 10, in <module>
    from pytorch_lightning import seed_everything
  File "\app_packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "\app_packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "\app_packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "\app_packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "\app_packages\pytorch_lightning\utilities\types.py", line 40, in <module>
    from torchmetrics import Metric
  File "\app_packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "\app_packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "\app_packages\torchmetrics\functional\audio\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "\app_packages\torchmetrics\functional\audio\pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "\app_packages\torchmetrics\utilities\__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "\app_packages\torchmetrics\utilities\checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "\app_packages\torchmetrics\metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "\app_packages\torchmetrics\utilities\data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "\app_packages\torchmetrics\utilities\imports.py", line 45, in <module>
    _TRANSFORMERS_GREATER_EQUAL_4_4: Optional[bool] = compare_version("transformers", operator.ge, "4.4.0")
  File "\app_packages\lightning_utilities\core\imports.py", line 77, in compare_version
    pkg = importlib.import_module(package)
  File "importlib\__init__.py", line 126, in import_module
  File "\app_packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "\app_packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "\app_packages\transformers\utils\__init__.py", line 33, in <module>
    from .generic import (
  File "\app_packages\transformers\utils\generic.py", line 28, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "\app_packages\transformers\utils\import_utils.py", line 35, in <module>
    logger = logging.get_logger(__name__)  # pylint: disable=invalid-name
  File "\app_packages\transformers\utils\logging.py", line 123, in get_logger
    _configure_library_root_logger()
  File "\app_packages\transformers\utils\logging.py", line 86, in _configure_library_root_logger
    _default_handler.flush = sys.stderr.flush
AttributeError: 'NoneType' object has no attribute 'flush'

Но тем не менее если запускать через команду briefcase run то приложение запускается и работает, gpu переключается, хотя я обучение пока не проверял

Все пункты по скачиванию исходника, установке зависимостей выполнял в точном соответствии с вики, но хочу заметить что если pytorch и xformers был скачан раньше чем установлена cuda то его нужно повторить последние две строки из 5 пункта в вики:

> python -m pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
python -m pip install xformers==0.0.19

И после этого режим gpu уже будет доступен

**Comment by wladradchenko** [comment]
Привет. В документации написано об этой ошибке. Откройте файл logging.py и удалите строчку с flush.

**Comment by anrej0705** [comment]
Я удалил строчку, приложение стало запускаться но gpu не переключается, хотя если запускать briefcase dev то gpu переключается и можно начать обучение. Видеокарта у меня 1080Ti, ос windows 10, камень ryzen 9 3900

**Comment by wladradchenko** [comment]
В документации написано, что необходимо скопировать библиотеки torch из venv в src/app_packages, тогда у вас заработает GPU
