### ISSUE TITLE
Mac OS briefcase run not working

### ISSUE THREAD

**Issue by Tern321** [wladradchenko/wunjo.wladradchenko.ru#46]
добрый день, после запуска
briefcase run
получаю ошибку

Traceback (most recent call last):
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/__main__.py", line 1, in <module>
    from wunjo.app import main
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/app.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by wladradchenko** [comment]
Привет,

Решение проблемы описано в [документации](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/%D0%9A%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-GPU-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8). Использование `briefcase run` на MacOS не поддерживается.
