### ISSUE TITLE
briefcase package, error in windows, the build work, the app open but cant compile anithing. 

### ISSUE THREAD

**Issue by zephirusgit** [wladradchenko/wunjo.wladradchenko.ru#7]
(wunjo) PS H:\ia\wunjo.wladradchenko.ru-main\portable> briefcase package

*************************************************************************
** WARNING: No signing identity provided                               **
*************************************************************************

    Briefcase will not sign the app. To provide a signing identity,
    use the `--identity` option; or, to explicitly disable signing,
    use `--adhoc-sign`.

*************************************************************************

[wunjo] Building MSI...
Compiling application manifest...
Compiling... done
Compiling application installer...
wunjo.wxs
wunjo-manifest.wxs
Compiling... done
Linking application installer...
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(7199) : warning LGHT1076 : ICE60: The file filF5E8DB8E4102951E3A509A6C325A79BA is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(7205) : warning LGHT1076 : ICE60: The file fil27F48996A851EEF3E69C743F02E20EC6 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(7211) : warning LGHT1076 : ICE60: The file fil84A5823952D12DBE3E58C5D215A6794B is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(7217) : warning LGHT1076 : ICE60: The file fil5F37FC6ED022340FBD6A66A552B5794D is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16983) : warning LGHT1076 : ICE60: The file filFA56B82AFD7E905E82BCC5549B58ACF5 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16986) : warning LGHT1076 : ICE60: The file fil1257BC7A45E9CCB44B5D58901B791E38 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16989) : warning LGHT1076 : ICE60: The file filFB1DEC1BC03800BCDBA8458D29D25DBD is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16992) : warning LGHT1076 : ICE60: The file fil4C4AE428D50598D6F28EEEFE74EBEFE1 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16995) : warning LGHT1076 : ICE60: The file fil639BB5793B86E2E02E52710602CC01EF is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(16998) : warning LGHT1076 : ICE60: The file fil7780A2CB4076B3C896045F19A87F400A is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17001) : warning LGHT1076 : ICE60: The file fil0C34475C8EF86122A73F3C3099D638E8 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17004) : warning LGHT1076 : ICE60: The file fil9B0C46927834A29B63685B46CCB9A5E4 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17007) : warning LGHT1076 : ICE60: The file fil40BA84BE3C99CF9874E590294E2929E7 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17010) : warning LGHT1076 : ICE60: The file fil209FAA2C5F012FD2DB9DEC3BF8F0001A is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17013) : warning LGHT1076 : ICE60: The file fil0B5B172BE478D66250D56ECA4D7D6FA3 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17016) : warning LGHT1076 : ICE60: The file filFD150E313DC40C5B46A8AF6222C4FC7A is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17019) : warning LGHT1076 : ICE60: The file fil1E5D34E22EA1D3FCE9A39C2B8BB435DF is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17022) : warning LGHT1076 : ICE60: The file filB5183121DCDD8DAC62871760FD7C1067 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17025) : warning LGHT1076 : ICE60: The file fil844C26D7E6C2CA410C89170A7F93476B is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17028) : warning LGHT1076 : ICE60: The file fil2DE1D004C173118DE042B0C259AA725E is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17031) : warning LGHT1076 : ICE60: The file filF9E7BF2B7E5B778DA311E58F09B9DA25 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17034) : warning LGHT1076 : ICE60: The file fil607120AB67899383769523711DB907C8 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17037) : warning LGHT1076 : ICE60: The file filCA8A5F8BA260A9C59BAEF6655CC45D04 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17040) : warning LGHT1076 : ICE60: The file fil001DA59D301F6A5E1881AFEE273D843A is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17043) : warning LGHT1076 : ICE60: The file filDCF180F036CC702E2F2F7EE4B3B566A1 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17052) : warning LGHT1076 : ICE60: The file fil7CFE43D0BE49FD060CBD1D46F0392078 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17055) : warning LGHT1076 : ICE60: The file fil250D619EC793734ACD252F8FD938470A is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17058) : warning LGHT1076 : ICE60: The file filF60DD131E7DE28A714BA64AE899BE919 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17061) : warning LGHT1076 : ICE60: The file fil3EFBA07AC3672BFBBB3D1E3580D0980C is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17064) : warning LGHT1076 : ICE60: The file fil712C897C067DDF03B95DA2C512903DFB is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17067) : warning LGHT1076 : ICE60: The file fil1700653885C516498B262C27DEA65153 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17070) : warning LGHT1076 : ICE60: The file fil3F240E1AA70835D2046F421BBE05B764 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17073) : warning LGHT1076 : ICE60: The file fil0F6E3CA59997F63AEEF9516DB50E9762 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17076) : warning LGHT1076 : ICE60: The file fil0038C5C2406506395965003D4F99DD14 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17079) : warning LGHT1076 : ICE60: The file filD2599584109A7FEDED1DD8510DD031A7 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17082) : warning LGHT1076 : ICE60: The file fil56FE8AACE2B03C50C184FA3C917ECF14 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17085) : warning LGHT1076 : ICE60: The file filAC3CE1EFC7FC38692594AA6D4893F70B is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17088) : warning LGHT1076 : ICE60: The file fil30F0C5EF90EA412C864433EB4209BA14 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17091) : warning LGHT1076 : ICE60: The file fil495B071AD61B20AD457E5005D6E22364 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17094) : warning LGHT1076 : ICE60: The file fil27228CA6FF465C5E37A2B50300613E54 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17097) : warning LGHT1076 : ICE60: The file fil8E4FADCC47EA4D581CADBF1034E01FED is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
H:\ia\wunjo.wladradchenko.ru-main\portable\build\wunjo\windows\app\wunjo-manifest.wxs(17100) : warning LGHT1076 : ICE60: The file filB8BBB096C9D7AA5E3F4A44245E1D354B is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
Linking... done

[wunjo] Packaged dist\Wunjo Wladradchenko AI-1.4.0.msi
(wunjo) PS H:\ia\wunjo.wladradchenko.ru-main\portable>

**Comment by zephirusgit** [comment]
ah! i find Wunjo Wladradchenko AI-1.4.0.msi in dist folder, installing :D

**Comment by zephirusgit** [comment]
dont work :/ 
The part that speaks does not work for me either, it asks me to create the folder and download a json?
or does the json have to download something else?
Yes, I can take a face, mark the area of the face, choose an audio, but he always tells me that he doesn't see the face or things like that.
try to use installer stable but it gives me python error. 
Traceback (most recent call last):
  File "\app\wunjo\__main__.py", line 1, in <module>
    from wunjo.app import main
  File "\app\wunjo\app.py", line 3, in <module>
    import torch
  File "\app_packages\torch\__init__.py", line 17, in <module>
    import ctypes
  File "<frozen zipimport>", line 259, in load_module
  File "ctypes\__init__.py", line 7, in <module>
ImportError: Module use of python310.dll conflicts with this version of Python.

im supous the python 3.10,

**Comment by wladradchenko** [comment]
Hello, zephirusgit,

It seems you're encountering an issue with the Windows installer creation via the Briefcase package. Since Briefcase is a third-party library, it would be more appropriate to raise this issue in their [official repository](https://github.com/beeware/briefcase).

You could consider pinning your Briefcase version to 0.3.14 as a workaround. The issue may be version-specific.

Regarding your query about setting up deepfake, I've recently updated our documentation. You can find a manual setup guide [here](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-manually-set-models-for-deepfake-animation-of-the-face-and-lips). Additionally, we have a Windows installation video tutorial available [here](https://youtu.be/2qIpJYhOL2U) (I will record this video on English after version 1.5).

I've also resolved some path-related issues specific to Windows in our upcoming 1.5 update. Though it's still in development, you may find it helpful to switch to the v1.5 branch, where bug fixes are actively being rolled out.

**Comment by wladradchenko** [comment]
Additionally, I would like add information what I use in project a Python 3.10.12

**Comment by wladradchenko** [comment]
By the way, I would like to note that briefcase package creates an installer. However, when you did a briefcase build. In the build folder, you will already find a ready-made application that you can use as a ready-made application.

**Comment by boltua1** [comment]
2023-09-05 10:36:51.181 | INFO     | speech.tts.synthesizer:_load_text_handler:353 - Loading text handler
2023-09-05 10:36:55.257 | INFO     | speech.tts.synthesizer:module_from_config:322 - Loading tacotron2 module
2023-09-05 10:36:56.249 | INFO     | speech.tts.synthesizer:module_from_config:322 - Loading waveglow module
2023-09-05 10:37:01.342 | INFO     | speech.tts.synthesizer:load_user_dict:267 - User dictionary has been loaded
2023-09-05 10:37:01.342 | INFO     | speech.tts.synthesizer:__init__:62 - Synthesizer Russian man is ready
New voice models added
2023-09-05 10:37:01.342 | INFO     | speech.tts.synthesizer:text_to_audio_gen:114 - ╨┐╤А╨╕╨▓╨╡╤В ╨┤╤А╤Г╨│
ERROR:root:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

**Comment by boltua1** [comment]
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()

**Comment by wladradchenko** [comment]
> import nltk import ssl
> 
> try: _create_unverified_https_context = ssl._create_unverified_context except AttributeError: pass else: ssl._create_default_https_context = _create_unverified_https_context
> 
> nltk.download()

From the provided information, it looks like you encountered a problem related to missing resources for the Natural Language Toolkit (NLTK). Specifically, the 'punkt' tokenizer models. Becuase of nltk.download('punkt') used urlib to download file. 

However, in some environments, downloading resources directly using the nltk.download() function can encounter SSL certification issues.
Your solution aims to disable SSL certificate verification, allowing NLTK's downloader to retrieve data without encountering SSL issues.

Here's what you should consider:

- Disabling SSL verification can have security implications. 

- If you decide to implement this workaround, make sure it's conditional, will be more clear approach to allow users to choose whether they want to disable SSL checks or not.

Thank you what you noted what users can encountered. I have changed the code in branch https://github.com/wladradchenko/wunjo.wladradchenko.ru/tree/v1.5.1 and the soon it will be in main. I used custom download function with requests without default approach of NLTK.  If you encounter bugs in v1.5.1 feel free to contact.
